FishJoy_QueryTool/FishJoy_QueryTool/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from FishJoy_QueryTool import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('query_tool.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FishJoy_QueryTool/query_tool/urls.py
from django.urls import include, path

from .views import Home, FishList, BaitsList, query_tool, delete, AddSpots, add, AddFish, AddBaits, edit, edit_record

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('fish', FishList.as_view(), name='fish'),
    path('baits', BaitsList.as_view(), name='baits'),
    path('query_tool', query_tool, name='query_tool'),
    path('add', add, name='add'),
    path('add_spots', AddSpots.as_view(), name='add_spots'),
    path('add_fish', AddFish.as_view(), name='add_fish'),
    path('add_baits', AddBaits.as_view(), name='add_baits'),
    path('delete', delete, name='delete'),
    path('edit/', edit, name='edit'),
    path('edit_record/<int:id>', edit_record, name='edit_record'),

]

FishJoy_QueryTool/query_tool/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse


class Spots(models.Model):
    title = models.CharField(max_length=50, verbose_name='Spot name')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')
    location = models.CharField(max_length=50)
    max_depth = models.FloatField(validators=[MaxValueValidator(10000), MinValueValidator(1)], verbose_name='Max depth')
    fish = models.ManyToManyField('Fish', symmetrical=False)
    spot_category = models.ForeignKey('SpotCategory', on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    def class_name(self):
        return self.__class__.__name__

    def get_absolute_url(self):
        return reverse('spot', kwargs={'spot_slug': self.slug})

    def get_edit_url(self):
        return reverse('spots-detail', args=[self.pk])

    class Meta:
        verbose_name = 'Spot'
        verbose_name_plural = 'Spots'
        ordering = ['title']


class Fish(models.Model):
    name = models.CharField(max_length=50, verbose_name='Fish name')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')
    average_weight = models.FloatField(validators=[MaxValueValidator(200.0), MinValueValidator(0.1)], verbose_name='Average weight')
    baits = models.ManyToManyField('Baits', symmetrical=False)
    fish_category = models.ForeignKey('FishCategory', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def class_name(self):
        return self.__class__.__name__

    def get_absolute_url(self):
        return reverse('single_fish', kwargs={'single_fish_slug': self.slug})

    def get_edit_url(self):
        return reverse('fish-detail', args=[self.pk])

    class Meta:
        verbose_name = 'Fish'
        verbose_name_plural = 'Fish'
        ordering = ['name']


class Baits(models.Model):
    name = models.CharField(max_length=50, verbose_name='Bait name')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')
    price = models.FloatField(validators=[MaxValueValidator(100000), MinValueValidator(0)])

    def __str__(self):
        return self.name

    def class_name(self):
        return self.__class__.__name__

    def get_edit_url(self):
        return reverse('baits-detail', args=[self.pk])

    class Meta:
        verbose_name = 'Bait'
        verbose_name_plural = 'Baits'
        ordering = ['name']


class SpotCategory(models.Model):
    name = models.CharField(max_length=50, db_index=True, verbose_name='Spot category')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('spots_category', kwargs={'spots_category_slug': self.slug})

    class Meta:
        verbose_name = 'Spot category'
        verbose_name_plural = 'Spot categories'
        ordering = ['name']


class FishCategory(models.Model):
    name = models.CharField(max_length=50, db_index=True, verbose_name='Fish category')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('fish_category', kwargs={'fish_category_slug': self.slug})

    class Meta:
        verbose_name = 'Fish category'
        verbose_name_plural = 'Fish categories'
        ordering = ['name']

FishJoy_QueryTool/query_tool/forms.py
from django import forms

from .models import Spots, Baits, Fish


class AddSpotsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['spot_category'].empty_label = 'Category is not selected'

    class Meta:
        model = Spots
        fields = '__all__'


class AddFishForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fish_category'].empty_label = 'Category is not selected'

    class Meta:
        model = Fish
        fields = '__all__'


class AddBaitsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Baits
        fields = '__all__'

FishJoy_QueryTool/query_tool/views.py
from django.apps import apps
from django.db.models import Count, F, Q, Avg
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .forms import AddSpotsForm, AddFishForm, AddBaitsForm
from .models import Spots, Fish, Baits, FishCategory, SpotCategory
from .utils import DataMixin


class Home(DataMixin, ListView):
    model = Spots
    template_name = 'query_tool/home.html'
    context_object_name = 'spots'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Home')

        headers = self.model._meta.get_fields()
        context['headers'] = headers
        return {**context, **c_def}

    def get_queryset(self):
        return Spots.objects.order_by('pk').select_related('spot_category')


class FishList(DataMixin, ListView):
    model = Fish
    template_name = 'query_tool/fish.html'
    context_object_name = 'fish'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Fish')

        headers = self.model._meta.get_fields()
        context['headers'] = headers
        return {**context, **c_def}

    def get_queryset(self):
        return Fish.objects.order_by('pk').select_related('fish_category')


class BaitsList(DataMixin, ListView):
    model = Baits
    template_name = 'query_tool/baits.html'
    context_object_name = 'baits'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Baits')

        headers = self.model._meta.get_fields()
        context['headers'] = headers
        return {**context, **c_def}

    def get_queryset(self):
        return Baits.objects.order_by('pk')


def query_tool(request):
    mixin = DataMixin()
    context = mixin.get_user_context(title='Query tool')

    if request.method == 'POST':
        table_name = request.POST.get('table_name')
        model_class = apps.get_model(app_label='query_tool', model_name=table_name)

        if table_name == 'spots':
            context['spots_header'] = Spots._meta.get_fields()

            value_gt = request.POST.get('value_gt')
            value_lt = request.POST.get('value_lt')
            spots_category_slug = request.POST.get('spots_category_slug')
            spots_category_slug_value = request.POST.get('spots_category_slug_value')
            spots_fish = request.POST.get('spots_fish')
            context['q_spots_depth_gt'] = Spots.objects.filter(max_depth__gt=value_gt) if value_gt else None
            context['q_spots_depth_lt'] = Spots.objects.filter(max_depth__lt=value_lt) if value_lt else None
            context['q_spots_cat_gt'] = Spots.objects.filter(spot_category__slug=spots_category_slug.lower()).\
                filter(max_depth__gt=spots_category_slug_value).select_related('spot_category') if spots_category_slug_value else None
            try:
                fish_m = Fish.objects.get(slug=spots_fish.lower()) if spots_fish else None
                context['q_spots_fish'] = Spots.objects.filter(fish=fish_m.id) if fish_m else None
            except Fish.DoesNotExist:
                pass

        elif table_name == 'fish':
            context['fish_header'] = Fish._meta.get_fields()

            fish_spots = request.POST.get('fish_spots')
            fish_same_cat = request.POST.get('fish_same_cat')
            fish_on_all_spots = request.POST.get('fish_on_all_spots')
            fish_bait_name = request.POST.get('fish_bait_name')
            fish_fish_category = request.POST.get('fish_fish_category')
            fish_spots_category = request.POST.get('fish_spots_category')
            fish_value_depth_gt = request.POST.get('fish_value_depth_gt')
            fish_fish_cat = request.POST.get('fish_fish_cat')
            try:
                spot_m = Spots.objects.get(slug=fish_spots.lower()) if fish_spots else None
                context['q_fish_spots'] = Fish.objects.filter(spots=spot_m.id) if spot_m else None

                cat = Fish.objects.filter(slug=fish_same_cat.lower()).values('fish_category') if fish_same_cat else None
                context['q_fish_same_cat'] = Fish.objects.filter(fish_category__in=cat).exclude(slug=fish_same_cat.lower()) if fish_same_cat else None
                context['q_fish_on_all_spots'] = Fish.objects.annotate(num_locations=Count('spots__location'))\
                    .filter(num_locations=Spots.objects.count()) if fish_on_all_spots else None

                context['q_fish_name_cat_cat_value_gt'] = Fish.objects.filter(baits__slug=fish_bait_name.lower()) \
                    .filter(fish_category__slug=fish_fish_category.lower()) \
                    .filter(spots__spot_category__slug=fish_spots_category.lower()) \
                    .filter(spots__max_depth__gt=fish_value_depth_gt)\
                    .distinct() if fish_bait_name and fish_fish_category and fish_spots_category and fish_value_depth_gt else None

                predator_fish_categories = FishCategory.objects.filter(name=fish_fish_cat) if fish_fish_cat else None
                context['fish_fish_cat11'] = Spots.objects.filter(
                    fish__fish_category__in=predator_fish_categories).annotate(
                    num_predator_fish=Count('fish', filter=Q(fish__fish_category__in=predator_fish_categories))).filter(
                    num_predator_fish=len(predator_fish_categories)) if fish_fish_cat else None

            except Spots.DoesNotExist:
                pass

        elif table_name == 'baits':
            context['baits_header'] = Baits._meta.get_fields()

            baits_fish_name = request.POST.get('baits_fish_name')
            baits_price = request.POST.get('baits_price')
            q_baits_on_all_spots = request.POST.get('baits_on_all_spots')
            try:
                fish_m = Fish.objects.get(slug=baits_fish_name.lower()) if baits_fish_name else None
                context['q_baits_fish_price'] = Baits.objects.filter(fish=fish_m.id).filter(price__lt=baits_price) if fish_m else None
                context['q_baits_on_all_spots'] = Baits.objects.annotate(num_fish=Count('fish__name', distinct=True))\
                    .filter(num_fish=Fish.objects.count()) if q_baits_on_all_spots else None

            except:
                pass

    return render(request, 'query_tool/query_tool.html', context)


def delete(request):
    id = request.GET.get('id')
    table_name = request.GET.get('table')

    try:
        model_class = apps.get_model(app_label='query_tool', model_name=table_name)
        model_class.objects.get(id=int(id)).delete()
    except LookupError:
        return HttpResponseBadRequest("<h1>Invalid table name</h1>")

    return redirect('query_tool')


def edit(request):
    mixin = DataMixin()
    context = mixin.get_user_context(title='Update')

    id = request.GET.get('id')
    table_name = request.GET.get('table')

    try:
        model_class = apps.get_model(app_label='query_tool', model_name=table_name)
        row = model_class.objects.get(id=int(id))

        if table_name != 'baits':
            cat_class = \
                apps.get_model(app_label='query_tool',
                               model_name=table_name + 'Category' if table_name == 'fish' else table_name[:-1] + 'Category')

            context['categories'] = cat_class.objects.all()
            context['fish_or_baits'] = \
                Fish.objects.all() if table_name == 'spots' else Baits.objects.all() if table_name == 'fish' else None

        context['row'] = row

    except LookupError:
        return HttpResponseBadRequest("<h1>Invalid table name</h1>")

    return render(request, f'query_tool/update_{table_name}.html', context=context)


def edit_record(request, id):
    if request.method == 'POST':
        table_name = request.POST.get('table_name')

        title = request.POST.get('title')
        slug = request.POST.get('slug')
        location = request.POST.get('location')
        max_depth = request.POST.get('max_depth')
        fish = request.POST.getlist('fish')
        spot_category = request.POST.get('spot_category')
        name = request.POST.get('name')
        average_weight = request.POST.get('average_weight')
        baits = request.POST.getlist('baits')
        fish_category = request.POST.get('fish_category')
        price = request.POST.get('price')

        try:
            model_class = apps.get_model(app_label='query_tool', model_name=table_name)
            row = model_class.objects.get(id=int(id))

            if table_name == 'spots':
                row.title = title
                row.slug = slug
                row.location = location
                row.max_depth = max_depth
                row.fish.clear()
                for f in fish:
                    res = Fish.objects.get(name=f)
                    row.fish.add(res)
                cat = SpotCategory.objects.get(name=spot_category)
                row.spot_category = cat

            elif table_name == 'fish':
                row.name = name
                row.slug = slug
                row.average_weight = average_weight
                row.baits.clear()
                for b in baits:
                    res = Baits.objects.get(name=b)
                    row.baits.add(res)
                cat = FishCategory.objects.get(name=fish_category)
                row.fish_category = cat

            elif table_name == 'baits':
                row.name = name
                row.slug = slug
                row.price = price

            row.save()
        except LookupError:
            return HttpResponseBadRequest("<h1>Invalid table name</h1>")

    return redirect('home')


def add(request):
    if request.method == 'POST':

FishJoy_QueryTool/query_tool/templates/query_tool/add_form.html
{% extends 'query_tool/base.html' %}

{% block content %}
<h1>{{ title }}</h1><br>

<form method="post" enctype="multipart/form-data" lang="en" class="add">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        {% if f.label == 'URL' %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: * (The way you want to represent your page, example: .../.../URL)</label>{{ f }}</p>
        {% else %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: * </label>{{ f }}</p>
        {% endif %}
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit" class="form-button">Commit</button>
</form>
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/baits.html
{% extends 'query_tool/base.html' %}

{% block content %}
    <table>
        <thead>
            <tr>
                {% for h in headers %}
                    <th>{{ h.name }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in baits %}
                <tr>
                    <td>{{ row.fish_set.all|join:", "}}</td>
                    <td>{{ row.id }}</td>
                    <td>{{ row }}</td>
                    <td>{{ row.slug }}</td>
                    <td>{{ row.price }}</td>
                    <td><a href="/delete?id={{row.id}}&table=baits">delete</a></td>
                    <td><a href="/edit?id={{row.id}}&table=baits">edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'query_tool/css/base.css' %}" rel="stylesheet" />
</head>
<body>
<div class="sidebar">
    <header>Select</header>
    <ul>
        {% for s in sidebar %}
            <li><a href="{% url s.url_button %}">{{ s.button }}</a></li>
        {% endfor %}

        {% block sidebar %}
        {% endblock %}
    </ul>
</div>

<div class="wrapper">
    <div class="page">
        {% block mainmenu %}
            <div class="header">
                <ul class="mainmenu">
                    <li><div class="logo"><a href="{% url 'home' %}">Fish Joy</a></div></li>
                </ul>
            </div>
            <div class="clear"></div>
        {% endblock %}

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <div class="footer">
        <p>&copy; Pevny Roman</p>
        <p>Offer your spot, fish or bait, for the sake of convenience of other fishers!</p>
        <p>For any questions or suggestions: romanromapev@gmail.com</p>
    </div>
</div>
</body>
</html>

FishJoy_QueryTool/query_tool/templates/query_tool/fish.html
{% extends 'query_tool/base.html' %}

{% block content %}
    <table>
        <thead>
            <tr>
                {% for h in headers %}
                    <th>{{ h.name }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in fish %}
                <tr>
                    <td>{{ row.spots_set.all|join:", "}}</td>
                    <td>{{ row.id }}</td>
                    <td>{{ row }}</td>
                    <td>{{ row.slug }}</td>
                    <td>{{ row.average_weight }}</td>
                    <td>{{ row.fish_category }}</td>
                    <td>{{ row.baits.all|join:", " }}</td>
                    <td><a href="/delete?id={{row.id}}&table=fish">delete</a></td>
                    <td><a href="/edit?id={{row.id}}&table=fish">edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/home.html
{% extends 'query_tool/base.html' %}

{% block content %}
    <table>
        <thead>
            <tr>
                {% for h in headers %}
                    <th>{{ h.name }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in spots %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row }}</td>
                    <td>{{ row.slug }}</td>
                    <td>{{ row.location }}</td>
                    <td>{{ row.max_depth }}</td>
                    <td>{{ row.spot_category }}</td>
                    <td>{{ row.fish.all|join:", " }}</td>
                    <td><a href="/delete?id={{row.id}}&table=spots">delete</a></td>
                    <td><a href="/edit?id={{row.id}}&table=spots">edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/query_tool.html
{% extends 'query_tool/query_tool_base.html' %}
{% block res_table %}
    {% if q_spots_depth_gt %}
        {% for row in q_spots_depth_gt %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.location }}</td>
                <td>{{ row.max_depth }}</td>
                <td>{{ row.spot_category }}</td>
                <td>{{ row.fish.all|join:", " }}</td>
            </tr>
        {% endfor %}
    {% elif q_spots_depth_lt %}
       {% for row in q_spots_depth_lt %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.location }}</td>
                <td>{{ row.max_depth }}</td>
                <td>{{ row.spot_category }}</td>
                <td>{{ row.fish.all|join:", " }}</td>
            </tr>
        {% endfor %}
    {% elif q_spots_cat_gt %}
       {% for row in q_spots_cat_gt %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.location }}</td>
                <td>{{ row.max_depth }}</td>
                <td>{{ row.spot_category }}</td>
                <td>{{ row.fish.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif q_spots_fish %}
       {% for row in q_spots_fish %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.location }}</td>
                <td>{{ row.max_depth }}</td>
                <td>{{ row.spot_category }}</td>
                <td>{{ row.fish.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif q_fish_spots %}
       {% for row in q_fish_spots %}
            <tr>
                <td>{{ row.spots_set.all|join:", "}}</td>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.average_weight }}</td>
                <td>{{ row.fish_category }}</td>
                <td>{{ row.baits.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif q_baits_fish_price %}
       {% for row in q_baits_fish_price %}
            <tr>
                <td>{{ row.fish_set.all|join:", "}}</td>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.price }}</td>
            </tr>
    {% endfor %}
    {% elif q_fish_same_cat %}
       {% for row in q_fish_same_cat %}
            <tr>
                <td>{{ row.spots_set.all|join:", "}}</td>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.average_weight }}</td>
                <td>{{ row.fish_category }}</td>
                <td>{{ row.baits.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif q_fish_on_all_spots %}
       {% for row in q_fish_on_all_spots %}
            <tr>
                <td>{{ row.spots_set.all|join:", "}}</td>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.average_weight }}</td>
                <td>{{ row.fish_category }}</td>
                <td>{{ row.baits.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif q_fish_name_cat_cat_value_gt %}
       {% for row in q_fish_name_cat_cat_value_gt %}
            <tr>
                <td>{{ row.spots_set.all|join:", "}}</td>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.average_weight }}</td>
                <td>{{ row.fish_category }}</td>
                <td>{{ row.baits.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif fish_fish_cat %}
       {% for row in fish_fish_cat %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.location }}</td>
                <td>{{ row.max_depth }}</td>
                <td>{{ row.spot_category }}</td>
                <td>{{ row.fish.all|join:", " }}</td>
            </tr>
    {% endfor %}
    {% elif q_baits_on_all_spots %}
       {% for row in q_baits_on_all_spots %}
            <tr>
                <td>{{ row.fish_set.all|join:", "}}</td>
                <td>{{ row.id }}</td>
                <td>{{ row }}</td>
                <td>{{ row.slug }}</td>
                <td>{{ row.price }}</td>
            </tr>
    {% endfor %}
    {% endif %}
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/update_baits.html
{% extends 'query_tool/base.html' %}

{% block content %}
    <form method="post" action="{% url 'edit_record' row.id %}" class="add">
        {% csrf_token %}
        Name:<br>
        <input name="name" type="text" value="{{ row.name }}" class="form-label">
        Slug:<br>
        <input name="slug" type="text" value="{{ row.slug }}" class="form-label">
        Price:<br>
        <input name="price" type="number" step="any" min="0.1" value="{{ row.price }}" class="form-label">

      <input name="table_name" type="hidden" value="baits">
      <button type="submit" class="form-button">Update</button>
    </form>
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/update_fish.html
{% extends 'query_tool/base.html' %}

{% block content %}
    <form method="post" action="{% url 'edit_record' row.id %}" class="add">
        {% csrf_token %}
        Name:<br>
        <input name="name" type="text" value="{{ row.name }}" class="form-label">
        Slug:<br>
        <input name="slug" type="text" value="{{ row.slug }}" class="form-label">
        average_weight:<br>
        <input name="average_weight" type="number" step="any" min="0.1" value="{{ row.average_weight }}" class="form-label">
        Baits (now contains: {{ row.baits.all|join:", " }}):<br>
        <select name="baits" multiple class="form-label">
            {% for bait in fish_or_baits %}
                <option value="{{ bait.name }}">{{ bait.name }}</option>
            {% endfor %}
        </select>
        fish_category (now is {{ row.fish_category }}):<br>
        <select name="fish_category" class="form-label">
            {% for cat in categories %}
                <option value="{{ cat.name }}">{{ cat.name }}</option>
            {% endfor %}
        </select>

        <input name="table_name" type="hidden" value="fish">
        <button type="submit" class="form-button">Update</button>
    </form>
{% endblock %}

FishJoy_QueryTool/query_tool/templates/query_tool/update_spots.html
{% extends 'query_tool/base.html' %}

{% block content %}
    <form method="post" action="{% url 'edit_record' row.id %}" class="add">
        {% csrf_token %}
        Title:<br>
        <input name="title" type="text" value="{{ row.title }}" class="form-label">
        Slug:<br>
        <input name="slug" type="text" value="{{ row.slug }}" class="form-label">
        Location:<br>
        <input name="location" type="text" value="{{ row.location }}" class="form-label">
        max_depth:<br>
        <input name="max_depth" type="number" step="any" min="0.1" value="{{ row.max_depth }}" class="form-label">
        Fish (now contains: {{ row.fish.all|join:", " }}):<br>
        <select name="fish" multiple class="form-label">
            {% for fish in fish_or_baits %}
                <option value="{{ fish.name }}">{{ fish.name }}</option>
            {% endfor %}
        </select>
        spot_category (now is {{ row.spot_category }}):<br>
        <select name="spot_category" class="form-label">
            {% for cat in categories %}
                <option value="{{ cat.name }}">{{ cat.name }}</option>
            {% endfor %}
        </select>

        <input name="table_name" type="hidden" value="spots">
        <button type="submit" class="form-button">Update</button>
    </form>
{% endblock %}